1 - The asyncWrapper function helps us prevents repetitive code when it comes to the try and catch blocks, making our operations smaller and our code cleaner 

2 - return next(nameOfFunctionCreated('Cannot find url', 404))


const getTask = asyncWrapper(async (req, res, next) => {  
  const { id: taskID } = req.params;  
  const task = await Task.findOne({ _id: taskID });  
  if (!task) {  
    // return next(nameOfFunctionCreated('Cannot find url', 404))
  }  
  res.status(200).json({ task });  
});  